# mosquitto_mtls.conf

listener 8883 localhost

# TLS Certificate Configuration
cafile certs/ca.pem
certfile certs/server.pem
keyfile certs/server-key.pem


# mTLS Configuration
# Client certificate requirement
require_certificate true

#Identify clients by their certificate's Common Name (CN)
use_identity_as_username true

# Authentication
allow_anonymous false

# Logging
log_type all
log_dest stdout